# Generated by Django 4.0.6 on 2022-08-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_data',
            old_name='employee_ID_id',
            new_name='employee_ID',
        ),
    ]
