# Generated by Django 4.1 on 2022-08-24 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge_nonstaff',
            name='date_time_out',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='badge_staff',
            name='date_time_out',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
